### ISSUE TITLE
Big Basic bug in StickySelection 

### ISSUE THREAD

**Issue by dsp0105** [mikinw/StickySelection#16]
Thanks for all your work, I was really hoping this would be working and I could do StyleToke kinda of highlighting in Pycharm but it has a basic bug :(

Example:
---------
def func():
my_var = 10
my_my_var = my_var +5

If I apply paint on my_var, it is selecting my_var substring in my_my_var.

Could you please fix by searching for variables only instead of just text in your algorithm?

Thanks!!

**Comment by mikinw** [comment]
The plugin works based on text. It does not know about any language specific things: nor keywords, nor variable names. For the plugin "my_var" substring inside "my_my_var" is the same as "my_var" anywhere else, and this is intentional. If you'd like to highlight all occurrences of a variable, you could use this: https://www.jetbrains.com/help/idea/highlighting-usages.html
Is this a functionality that you were looking for?

**Comment by dsp0105** [comment]
Thanks a lot for getting back, sorry I could not check back  earlier after raising the issue.
That looks like what I want, I am trying it but it does not seem to work, will dig deeper. 
One question though, can it do >1 variables (like notepad++) does?

Thanks for your time :)

**Comment by dsp0105** [comment]
Thanks it is working 👍 
Only gripe is that only color is used for highlighting usages for all selected variables. Do you know a way to use different colors?

**Comment by mikinw** [comment]
I'm not sure I understand what you mean by different color per variable. You can create any number of paint groups, and use them if you'd like to have different colors

**Comment by mikinw** [comment]
I have added a feature to paint _only_ the selected text, and not all occurrences. This may help in your case.
If something else is missing, please open a separate issue. Thanks!
